# Generated by Django 3.2.4 on 2021-07-17 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_requestedservice_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedservice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 9, 59, 36, 166475, tzinfo=utc), verbose_name='Created on'),
        ),
    ]
