# Generated by Django 3.2.4 on 2021-07-19 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_requestedservice_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedservice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 6, 15, 28, 910416, tzinfo=utc), verbose_name='Created on'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='comment')),
                ('rate', models.IntegerField(verbose_name='rate')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client', verbose_name='client')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.worker', verbose_name='worker')),
            ],
        ),
    ]
